### PR TITLE
Images from gallery can turn buttons and scale 

### PR DESCRIPTION
**Pull request by sktbrd**
image

OBS: I tried to re-use the other molecule I created for the Iframe scaling, but I could pass props for defining max and min for the slider in the inputs selector we can probably reuse more molecules if we can pass props from the fidgets

```js
const ImageScaleSlider: React.FC<ImageScaleSliderProps> = ({
  min = 0.2,
  max = 3,
  step = 0.1,
  defaultValue = 1,
  onChange,
})
```

So I had to repeat the molecule and hardcode those values, appreciate any optimization insights.

### CODE REVIEW

**Comment by sktbrd** [comment]
@j-paterson that one is good to go, simple 2 files change

**Comment by sktbrd** [comment]
@j-paterson  this one introduces a newInput, do I need to add this new input in any config file ?

**Comment by j-paterson** [comment]
Yes, you should add it to the inputSelector on line 36 of /src/common/fidgets/index.d.ts

**Comment by j-paterson** [comment]
@sktbrd - closing this since the other one was merged in

**Pull request closed without merging**
